# -*- coding: UTF-8 -*-
"""
#!-------------------------------------------
# Copyright (c) 2019, Horizon Robotics, Inc.
# All rights reserved.
# \File     hello.py
# \Author   Yingmin Li
# \Mail     yingmin.li@horizon.ai
# \Version  1.0.0.0
# \Date     2019-02-20
# \Brief    implement of hello.py
# \Python   python3.7
# \DO NOT MODIFY THIS COMMENT, \
# \WHICH IS AUTO GENERATED BY EDITOR
#!-------------------------------------------
"""
##
import matplotlib
matplotlib.use('TkAgg')
import numpy as np
import matplotlib.pyplot as plt

X = np.linspace(-np.pi, np.pi, 256, endpoint=True)
C,S = np.cos(X), np.sin(X)

plt.plot(X,C)
plt.plot(X,S)

plt.show()

##

